/**
 * Every user-facing string lives here so the copy can be reviewed and edited in one place.
 * English only (brief §6).
 */
export const COPY = {
  siteName: 'Token Metropolis',
  tagline: 'The world’s biggest AI platforms as a living city, sized by the tokens they process.',
  loading: {
    title: 'Token Metropolis',
    status: 'Switching on the city lights…',
    failed: 'The city’s data could not be loaded.',
    retry: 'Try again',
  },
  hud: {
    todayLabel: 'Tokens processed today',
    todayQualifier: 'all 15 platforms · since 00:00 UTC · estimate',
    arrivedLabel: 'Since you arrived',
    rateLabel: 'Right now',
    perSecond: 'tokens / second',
    range: (low: string, high: string) => `Plausible range ${low} – ${high}`,
    updated: (ago: string) => `Data updated ${ago}`,
    offline: 'Showing the last saved copy of the data — the latest could not be loaded.',
    methodLink: 'How we estimate',
    dataLink: 'Data view',
  },
  tiers: {
    reported: 'Reported',
    derived: 'Estimated',
    modeled: 'Modeled',
  },
  unchecked: 'Not yet checked',
  uncheckedHelp:
    'A published fact we have not yet checked against its source page (see the verification backlog).',
  tierHelp: {
    reported: 'Published by the company or a primary source.',
    derived: 'Calculated from published figures.',
    modeled: 'Relies on at least one assumption with no public data.',
  },
  table: {
    caption: 'Estimated tokens per day by platform (central value and plausible range)',
    platform: 'Platform',
    parent: 'Company',
    perDay: 'Tokens per day',
    range: 'Range',
    tier: 'Tier',
    latest: 'Latest published figure',
    scope: 'What is counted',
  },
  footer: {
    disclaimer:
      'Independent project. Not affiliated with, endorsed by, or sponsored by any company shown. Figures are estimates unless marked Reported.',
  },
  panel: {
    close: 'Close',
    today: 'Tokens today (UTC)',
    now: 'Right now',
    perDay: 'Daily rate',
    sinceLaunch: 'Since launch',
    tokens: 'tokens',
    perSecond: 'tokens / second',
    gpus: 'GPU equivalents',
    gpuUnit: 'H100-class, busy now',
    power: 'Power now',
    water: 'Cooling water',
    waterUnit: 'litres / day',
    infrastructure: 'What it takes to serve',
    infraNote:
      'Hardware, power and water are modeled from tokens with one H100-equivalent efficiency figure for every platform — the biggest uncertainty on this site.',
    latest: 'Latest published figure',
    how: 'How this estimate is made',
    snippet: 'checked against a search summary of the source',
    range: (low: string, high: string) => `range ${low} – ${high}`,
    extrapolated: (days: number) =>
      `The latest figure is ${days} days old, so today's value is extrapolated and its range widens with time.`,
    localTime: (time: string) => `${time} local time`,
  },
  views: {
    label: 'Inside this HQ',
    overview: 'Overview',
    offices: 'Offices',
    hall: 'Server hall',
    power: 'Power & cooling',
    lab: 'Model lab',
  },
  offices: {
    intro:
      'A cutaway of three office floors. More desks fill as the daily rate grows and as the working day starts at the HQ.',
    honesty: 'Desks and people are a visual scale of load, not a staff count.',
    traffic: 'Traffic right now',
    trafficUnit: '× the daily average',
    trafficNote:
      'The time-of-day curve is an assumption — regional waking hours plus the one published production load curve — so this figure is Modeled.',
    hardwareLabel: 'Desk hardware',
    hardware: [
      'Boxy monitors — the lighter load band',
      'Flat screens — a heavy load band',
      'Holographic panels — the heaviest load band',
    ],
    bands: (a: string, b: string) =>
      `Load bands follow the daily rate: below ${a} tokens/day, ${a}–${b}, and above ${b}.`,
    typing:
      'Screens flicker faster when traffic peaks. Lights follow a typical office day in local time.',
  },
  hall: {
    intro:
      'Rows of racks grow with the daily rate; their LEDs blink faster when traffic is above the daily average.',
    honesty: 'Racks are a visual scale of load, not a count of real machines.',
    accelerator: 'Likely accelerator class',
    liquid:
      'The coolant pipes are illustrative: this accelerator class is usually liquid-cooled at scale.',
    air: 'No coolant pipes are drawn: cooling for this hardware varies or is not disclosed.',
    sources: 'Sources',
    classes: {
      'nvidia-ampere': 'NVIDIA Ampere-class GPUs',
      'nvidia-hopper': 'NVIDIA Hopper-class GPUs',
      'nvidia-blackwell': 'NVIDIA Blackwell-class GPUs',
      'google-tpu': 'Google TPUs',
      'aws-trainium': 'AWS Trainium',
      'huawei-ascend': 'Huawei Ascend',
      'amd-instinct': 'AMD Instinct GPUs',
      mixed: 'A mix of accelerators (not disclosed in detail)',
    },
  },
  power: {
    intro:
      'The substation feeds the campus; cooling towers carry the heat away. Both gauges are live, and each log scale spans every HQ so the needles compare.',
    powerGauge: 'Power now',
    waterGauge: 'Cooling water',
    inputs: 'Inputs',
    formula: 'Formula',
    checkedSnippet: 'checked against a search summary of the sources',
    checkedPage: 'checked on the source pages',
    labels: {
      throughput: 'Tokens per second per GPU',
      kw: 'Power per GPU',
      pue: 'PUE (facility overhead)',
      wue: 'WUE (on-site water)',
    },
  },
  lab: {
    intro: (name: string) =>
      `The ${name} lineup: oldest on the left, and the newest glows. Faceted gems are the company's own models; pale stones are other companies' models offered here. Flagships stand taller.`,
    capped: (shown: number, total: number) =>
      `The display case holds the ${shown} most recent of ${total} models; all are listed here.`,
    list: 'Models, newest first',
    choose: 'Select a model to see its details.',
    released: 'Released',
    firstSeen: 'First seen',
    context: 'Context window',
    contextUnit: 'tokens',
    notPublished: 'not published',
    modalities: 'Inputs',
    origin: 'Made by',
    own: (parent: string) => parent,
    offered: (maker: string) => `${maker} — offered on this platform`,
    flagship: 'flagship',
    offeredTag: 'offered',
    source: 'Source',
    pending: 'not yet checked against the source',
    empty: 'No models are listed for this platform yet.',
  },
  time: {
    label: 'Time machine',
    play: 'Play the history of the city',
    pause: 'Pause',
    speedLabel: 'Playback speed',
    speeds: { week: '1 week / s', month: '1 month / s', quarter: '1 quarter / s' },
    slider: 'Date shown',
    live: 'Live',
    goLive: 'Back to live',
    historyBadge: 'History',
    historyNote:
      'Past days are read from the same growth curves as today: figures before a platform’s first published number are modeled, and ranges are wider.',
    date: (iso: string) => iso,
    todayLabelHistory: (date: string) => `Tokens processed on ${date}`,
    todayQualifierHistory: 'all 15 platforms · 00:00 UTC to the time shown · estimate',
    rateLabelHistory: 'At the time shown',
    reachedLive: 'Back to the present.',
  },
  launch: {
    active: (model: string) => `Launch day: ${model}`,
  },
  race: {
    open: 'Race',
    title: 'The race for tokens',
    subtitle: 'Daily tokens by platform',
    close: 'Close the race',
    scaleNote:
      'Bars share one linear scale (the leader fills the width); thin lines show plausible ranges.',
    notLaunched: 'not launched yet',
    rank: (n: number) => `#${n}`,
  },
  feed: {
    open: 'What’s new',
    title: 'What’s new',
    new: 'New',
    empty: 'No model launches yet at this date.',
    source: 'Source',
    toastLabel: 'Model launch',
    close: 'Close what’s new',
  },
  controls: {
    scale: 'Building height',
    log: 'Log scale',
    true: 'True scale',
    overview: 'Back to the city',
  },
  noWebgl: 'Your browser can’t show the 3D city, so here is the same data as a dashboard.',
  skipToData: 'Skip to the data table',
} as const;
